# Generated by Django 5.1.2 on 2024-10-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notification_recipient'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_979360_idx',
            old_name='notificatio_recipie_8bedf2_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.IntegerField(verbose_name='recipient'),
        ),
    ]
